---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: coder-oidc
  namespace: coder
spec:
  encryptedData:
    client_id: AgAxEZTfvdXqstSzX2/62l5jL8wNC5wfgTQDogouo3PhGVUj6BV3xpUlxxAiqeKsiH+vp8h8qCa1HSBkGWhYRNYRkL7VgBAKNFx599xexaCD4zxHB8T/c7hb3pcpEMONeYenZcDy5P8KU/pIWAYRGTAQ85+kRsQA/RNLKoparp1cn2A/RYBBpR1NYqMvpR6yOsnLJLxWUP1AGRv2wd+PJVY1CI4QP50qrjPyGOTE+wIiNib+48k91ZYgL5AlQGTZbFcpXtRmcUPNDnuHO9evasidpVJyr/3IyhComsu27iW7QfcP2O8aUi4uzwvxGV/TGwOAXZRjZEp5c0kbSEU8s+keP9rQZ+F+IJOKsAwgJzLp218+RCuNfx1J+ehmFf9F+g7qR8Xc14YOFzwDbRdWk1SsEtesRCh2OGy/OEwFPiRSCNhIVspV2aUHLDdJWpj/Mc6VNncn0DT5e67xDvYUyY0HzB3p7LvLrvSKRniL1OQjomKELGMNiryFeV0EVueSdj2FmqBs/h8S0KjB78F0fYlMUrn24F4IzRNMFfji5byOkWtlPdV5YZ5i2xJxpuYvmbqyvBUHXcK3O2Ls1aer/rbRnBzri3Mz3BSSlirhNbUI4Em5ed2hiZUPB86p8zXKkvBZsXKFkWxLwKu7qx+D6IlYme/WQw7iPbtOJ6FB2SjY+irbMqkCTcaQvmt+QA3ibfU4SptuCw==
    client_secret: AgBS9rJ1gHxEvXzrPyTToyOMES65L2IkhEnXTALduh/neGQuvKOJJjenlv5+5kz/3QxAueUt96PGMGPRRZ91H52DUcBhm9IduFqxHGG5rbSBHMRZen6pypCH5DQuV4NNGYa6YTo6DZlvPpqzJ+dgpYciRtMHDQ5lr+c1GwosJdDkH5257ma5c3AdLBkeUtioZVSmrlz4QYT5CpRojZhajKVTT+g4Iyi9apFZZRb9wriS4PWpg+tA5SIT+2IjfpqvXzFjOcea723vQwVJ7zqQj5A4Zep5YNns1XCQlgAT9IxlbWmKMpSuyoVy6kyDMd91TPEBDcnQut01qTLxMQqNpMMTsnXJbQqjwVo2Zu5ZXgUWfqJUqNS2cyHlb7vnj/1a/5rVbS9gf35Qm5M7OKblLXOm3CYDp5xsI47oOya+0GUHfbHTP/Hf/7wwuelxciATd89qfnF6POO3PzxU13n56n+AXqJE8BCLlVa7bwoDJESmKrEDWjniZuZJdWY5xNq6dpTja0GxeHJblb2W0LT3T1T8UjVOEh5Txsz+gpcg2UJ67PSBiD1cR2RbO1SCecjkytKrJ4q4TZ7aqOwQpgx1d3N8g50l6QjCWfc6+J+0iOr5qMwhlhOWk1paXeaWGw2N2voIf79D/mT6Ly0mfIA1F1GedHb1exGRXb71W4lR+syxXW5J8evTJrjbsHU0pRXuLr23zpDrgWcPyEOczWsV02ekgmHqZoPz4pHlPzAZcD2GNg==
  template:
    metadata:
      name: coder-oidc
      namespace: coder
    type: Opaque
