---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: coder-db-url
  namespace: coder
spec:
  encryptedData:
    url: AgBr/40WhEsjq11vhiy8vqIxnm+HzyP2xd2I/qGImnDn1tXmSW3zAJK7799qXBVsaXwnFsFAN63WGZRcUSAlXGLqWI42Lkj1RU47Bysz7V9viLB1hY94TRM33/v5syy/x3AbWgu91EXsC0Cjs+nwTC36WT/yZqWOQg2hXgMfLnwijrhOCodz/KiZpxZ55XUbnnA6lj5WyHT+XwcBkIi9uv02i9rSLPdEIQYIZ2jd4JPT2jVXs2NnwmQKsCerhIJA7cyH7xk5xt6TKU7rexIdZCDZF5IIEsIdKstU3jGd+KG/fE/P2lQl+2x6LzfumPo6BCDbKfBvJK/IDHhg4LRpKuSqIiZc7pzLBJg3NcflfIuwi6yH9IqiYyw1yXPStQCdWAM7uOa9Y3lkeBeBwPDI+YWJmgH7uhBS8ea8cStbe0zrP2IYTrYJLAXppvLMf69/t2YFt55TQ+XTFEa5T9V152XUYl+7arbdCxOyNDB4eiQxb0MiuQuha2mHGa//7SyZ7tzbQMBe7LDcRqwGIZYOTV9L20ZiXACPBH31bnOwETI/nuuEFNPdiwp5mM8LA8sQg6ceHLJheuFIA+xkMh6Yye9hpxDyhD3qlNr3uopiWDjpo+dKsyw/vyA2NTm+1hAUieLmmb60MesMLMlR9A1bJBvkF1Xf5/xD9WTGw6Z7P3rM0Z2ckjTSHBFd1iUOgXCOk0Bd3MfIV5DCsSqe+cVblxJxxjku+ysyYdUIi6D95XGVDYsGdM1w4mUkICBqiUwFHnIqq7kpzqtNHoZoprf1GOuGQk6+AhDMLMxxJ2L5a1hlcegc6GZXHkD4buQpSUemldS13+t/9Q2prRVD6cuqIHVrRuN+4vzIXAh6tycNWbARR9RccYXtC1uSpEm9wT41TtgsBw==
  template:
    metadata:
      creationTimestamp: null
      name: coder-db-url
      namespace: coder
    type: Opaque
