---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oauth
  namespace: infra
spec:
  encryptedData:
    client_id: AgBQvQgQqS1V9jAjfgNM4yANZF1JDhg6BvnBT3sotJfP46v+j1j0gtzaOWzjS0SX+lLOzz2AwAZmh6vvhPK1a1Dr9mtcNFjwzhtPjdlZZlcTKKiOCh3ZfYiAMSXaZw3KNGCLVJs0cZ/B38WZpAqWHxQntxCi99NKyNQk051znTL+trSq09s1Xkut+ESqMfAyVdgCiLG1zpczK8+ah9JBTfK4JcgK9wZceqxyLgGQCg4icykA2mrloeH0rryeZDnVEqi0OJxCeHfb/6Xt79zqHtzbSgLk3Mm1zAdWa8OsfdK+B79BtripdCBCeJ6PdkZJnFTzyVNYmptxDroRWddtsRYc3PUuGosxALs7TxPBSne64FD33svVTMlJoTL07OSCP9Lgr6hHxqw6Binu7yfcOl01o2eR9V2OGX3zXMB/3M2gnmufpzbkdF7YsGS173XdPZAzY46nzGhLZ8ux8lVKovk/D2wG6HOidTFGrKRC3C4Q01yDX78ydz1uov6HXrE3KKlbpJ8xwUpI/36DL4CByZ5DO3otxLIWISSlcv0CKd6FtitjgDpBvAE5KOrDDJeYNbe+m3SNuyohBlSeV4LGPp34td2yW/zAMoCevnHN/m3z7NKY+2luz6fSkOrwSmhCk6jQzbLmyvwe2BGRDFmv2yXqpuHRjgFsNzq6baKx8jniGvkKj+5HH4emjgjoQ0lnpfsWwIBG6ZU=
    client_secret: AgB9KUfkxI/RUlw3eE80OvlSuSWvtYptDTPlOxn87ICM07WEz5OfbPBxsLbhoJMRe3Q31qonLpsLXJeGq4TyFV5WcAqBYXXD9Q/84uHWUvhBoz+hkf2HuUn5llvdKZYOjzc6LNemTy/Z6W6pi1AGgrKuyyKhlX4hFVjeh/0+xnWLSERWqleEW8Tsnoo8vAN3AKD8eBtnvvJ8VLd9bZpmlOfmb47kNmEFxGKFCWDAPIkHDmb/vQ/L6DOPHEKqWI93e7Qg4ZlCBGhBGfg/f9V/UEi7mJlHWAitfsoicHjmSllwdxjVM4kJOTd8GDI/Q/k8tCnku5lMYcfOno1PQk3B7ggR/adw01YAWxVYxvjpu8Wc7IkOlsWHi8FMBKtmSFa7dz7eCbYX0DTtL40jJocaPQ/4rdpUsATqKXdACME8dQ9lbhFh8RlM39yrWtSfOfrGBoHOY3oheL75YpOekcMRQMg/5k2kLWYyBhLfwYIKogFYNwaZ/o9iM91Q2Sayg28zrXK7ya+f2eroB6CTOXZjpo2Ub+VcPLpbLnconvs2xjrP8CksFGqAGrOSQxu1z4tUIdploh8oIPqB683gMTRgQSnux6muNDVKLXZzPrD3IJAk0HoVm3Lp2tKyJQxiFy1y1mJV82BAFFhEix25RLPO2zGOntZs43AjLbZyvBOJhpl8u/1EtDYn5XQ5HPEY4pLlxmGO0QBf/n+sjjlpt9aC4jlKfsOdIoKntiImoiOfHjPmkQ==
  template:
    metadata:
      name: argocd-oauth
      namespace: infra
    type: Opaque
