---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: coder-oauth
  namespace: infra
spec:
  encryptedData:
    client_id: AgDU4d2FHdezOcQFyILpViCbSgDjw/39yKgMg5XopTJUOH1dZg3e+qESpywqpgc9CsGaAaquNmnBTCTMmw4MoB98MKt1XobyGxdI0MV5mv0R3kikWPIsP4szbVYh03NK95DP0s5aKoVMyykVK7ZYXkbZH1elMAeSlblxaareTSqNBWPt+fr2VZ3k6HHSl2UzGhtpgMvFqDoIlgb9gHgmLN2gm2CCcd3yJQPhXfNb7a9UQG+JfsqMoLenxBqActhUmI5bsQW4fKdHsvB3UJkXx8LxnmcNlLuFkeXz2x3YPwd1T2OYoH80qrNQeCwfhADb+uHWwfqpma01+Icq+uqEznPQBSf/hdpvo9NECzyjpdnZNEmd4CI2rFN90czbW7INhDuBpL0RVxOriCRhBk4DRFAIbgNb8QhcLD6dRGcMhwMHMoFyUlh0/mkhcCiF7hmqbdH8HigxTNKz0YdNxKm4nT8Gfkt4lvLnwSAbt+0N+Cui5S/EPmxkY2lnyR53s+RsvQ1H0vMwpxL3iGA1IgFDvmh+AgpRkuFrIAC8m4kZDSzU1p5dOPCAnQOkWa9zKJkb7ss8bnxLrA2HyUEHePz0lUbfCNUzt+dgx55IT74uf5VIhCxMy1m1dxKC+uTzZD+ooUJZKzv/5JfvadNsmByFPnKpGBphIj/ts1gQBHyE6VgoFZyi1cXJUsJb3xR87naP4x3N840g+w==
    client_secret: AgBGXXTye0vQRd4HfLsWn999xni57AbderhXWLR9rPgwQElx83hGfuC9OpZP/yB442X2jsRkyjs9XW/5CHjKw7Ip7nKb4q4kgIgsyPw5ZHEr6FtISOQrr4bUAr1K7qLIQZW5HdXrfX0OIgdtAzp5wbo6xIClI3RRak2/u6ndSQt22tR72kIi2WgFbopFSF2ig4y/ALEo+fcXA0jlXxnjTxLcQPDkPsVzYogQfP/FVV/FRbyyh0k92iosKO2CPid+96D7L0jQbXUSbOI+eZLGc3O1wlC2s9yAfkgJwbv0a0EpWj7J2o6AIgvSCGXYDigDpRXNab0AhcCcP9gpeboeWIlBFvlgUHXETUGlSJvjOBxMMqI5LrGK5qspv250IaAopY4EuRqUK7qlWvoNiQZmzSy2W0bNVqfnB5XDHYay9zUjk/XftirhiMGjOjJpeI0g6utHoryy5Nm7d2ZZL5dSAZ4IdEM/sVb3K/qfdmkIckgpr2KhYr7bBDqlY/l2MUavXQHgrUSYyse/YEFjp/UbePAXHEV0vl590ibnlj+W21cOD2lPh5TIFVMQJ0J5S0kLGw0xjPkkjzfSVCe3s5JuucxnCeduDbHzkTjpD6qpIBRwnIUXxrXuOdTo/BSvQ0J7+cQLaCp8KMRo+9094YHwimHDnpkWDxb/lytv9UkmEr+C2D2ucyOHlYJcPx7sH+ooUkS+j5TeoGbOjkrWDT8sQHxSiECo/MWAfQj7PRoDqeG0Ug==
  template:
    metadata:
      name: coder-oauth
      namespace: infra
    type: Opaque
