# SealedSecret — hydra-db-url
# DSN: postgres://postgres:<password>@postgresql.infra.svc.cluster.local:5432/hydra?sslmode=disable
# ==============================================================================
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hydra-db-url
  namespace: infra
spec:
  encryptedData:
    dsn: AgAGggULW/zaECIe60bcwpnX4+XLR2IfXdeey5yiitYs+wpAdRP1qHGJqDQ4CdDwYbKThg6Flw0u64w2RgJi8lMi26wA8vscIr+HjiRRkTgokPe5xJXCHsf20jq/DP8Hv6hdVSklXBcP0bIk4F0L/FVej8sl4imlbZecwtyJUOmxVrJyJeeZPGXQ+W5nYlHYXuefrR5i6yiqUPDJooBqsSYhy7dlQ5yil9axhJz2X/ZQkYJmOHSF9yVgay/7AfDXOIXAqTG/PPhMmjZr82eZw80iGQCKGZf4lkv4Z+WAejshug+rVOJ0vKCxbfQ9+hKLzhNhMnoO6aCGZ44W9txxy2T7rsU7Ghjy5wKDRDZ8AhjziXRWDQaoZM1+3+yS22ZRpkOiwUmjCZIB90vTJJsJgSGvSGpr2qhtl/ufI3wtePzGTB3kT8xxO5eJjo66mBCGrRBbGgbU8vE6OU2+/r05E78yV02RRKvq34Ss25ElRdx5dKJ+6ZXqSrD6qj841e1HBz1Jq3UITJ45Owlfro0Tlg6H6AhBHsl23odLjYxa8OfROfK8lfld3ig/RQ1xHNleaIeuEl9halUcu2jqLreR5LCIE589NTX855e14jK+4HK4erysme0T4lgtIStv4I+bzYKp4TiXTgnf6Se8m4TEVBgp4ItQrdt68573DCybX+hoLEu98OytXdKYQELOnD2SITes2KaGS02ZEHUMsf1DbpvRon/3JN47WDEBlv9mL8753LD69QCJWwx/mSQeCsVOLE22lL+tALMlz5rrwLxidt64+xBAHf3HZoa2An8bEozShoWgiRxYh5sa9VtKBxwtO7nx/tYjMf6nhFNw361ltG8K/z3o2lLHZUpiL4LXA/VJluGCAYAVPa5dmiB8D+GZfQc2xQ==
  template:
    metadata:
      creationTimestamp: null
      name: hydra-db-url
      namespace: infra
    type: Opaque
