apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/ecoma-io/gitops.git
      revision: main
      files:
      - path: declarative/platform/*/config.json
  template:
    metadata:
      name: '{{.path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{.syncWave}}'
    spec:
      project: platform
      source:
        repoURL: https://github.com/ecoma-io/gitops.git
        targetRevision: main
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true          
          - ServerSideDiff=true
          - PruneLast=true
