---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kratos-db-url
  namespace: infra
spec:
  encryptedData:
    dsn: AgBS24XB6q0N0M1pOKyfhXgOcbC1eb0V16Bhjg7ochL3cdTrwZJfXdux56JxammHHS5/HGuT+vZirq6dboc1oKezSD+OMHp1k9/iQ4CcGJdbp9nD8pCD2KB7hT0aV3QQeKw1n6DWUopcrH5Ldkqqr6ToLveRalOipMkI5pmpYO4w/8TPsOmc8bPhrpoC1fwG2Wx0oxYWNwOFjP0+1uQuitm3rXlVu3T0C+7mlSr//Dh/rOfdsFNm3YT78tpjHK3+5y0SBso3VqM/gcBc42Lk6++E2ZsHz/itFZQF5ipNuR5aQbnXkF58mNcFvN+mBzjtSwKLfRrk6SxAcOEu3jiK3jwCxaiJ3aG5yPVI1zQp4TeqOgI11ZF8QDPGmDV7KNCANVGjVk0I5xVfH3lhap9IEWbg1Z4l4w2i0DqAiegd24pVLkRteicQeaTdzDFM0LTKQ/e0s7pXrAOOWLIW4a7n6B3nuyfQiDuwPwvODrBK1iC83wBcVQ8LbgAp95cnHj7agNRX4iOjkhC32byvoRZnrRBQDr0ym0C1TbKtGj+sJNQAvyjdrK9jhm96ahHxOKkggTpgL5eRvgWMCgRSBF+VFBaGHwkyb+eG4F9fXouzdduOIVXQ5AiQlbq1TbB4CFqb5BnxxPvcWGq4ZrCugpy8/7tQPRPVvVk5HS+vdrsFmVMPyl3e28+42YLvsTG+McV69EWmamwtcDdwYZlEwsZKWrfPEw34E2M0n/vlwJF3wzqEqb4Uco27CJlIEm+LIaIfeenG5Bk749UpcCPTyvDQLiy1D56Y44cZWd6Vqs7HDRD7Upbc4DTLuY70Iu+L15E/yubFcphLKwC6GUyt0q3g69DASeHOUFp9WjRZa9z45/VcIoRUBD7LGjICay1zBAq7e9OwN68=
  template:
    metadata:
      creationTimestamp: null
      name: kratos-db-url
      namespace: infra
    type: Opaque
