---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keto-db-url
  namespace: infra
spec:
  encryptedData:
    dsn: AgCkwvPl52l/j5hqoeezuSv26Gi38CmwcwptPkC6hcT7k9X4ARPMokuwDir9LbGURwBnOTq3keaJUYFtH/SREN0YvJK1yAdCysNPUz+ckqXWumI0gcUn8kSJIGB6kxsDYzPuyhz78Q1g3BtTRvMevQFSAXN6ZGAX9RKkHtSV5Cpf+0pZYryH/zV0RkH3zsjckcR2UQeTL1N2Anj7VYkM3kY2wnygFd8UwjcsNjM4mkYktT4Vrb3o9k5/QK+XvNY0gsc0FfXTknf8OVPOdTDrYpxnXwsfp0AJmqehAgQys2IuDJvbotpaOG3se6r6XWgB23BcMU6ZwletDD+bm2OXxWotAvuRQIKa1/x4SYXEcib8l/0SvmOVz8pHTY9hsPBogbzu968FnbCyt047aHblh6/0/58Ua7OA/+0V55BOcBBFPHC+VkA3RABE3A7AFEeMTjReYLQJvaLNxsmk62olLysipv6hCbw7ezuIUwCKuIYiF0aUJDGzOFc463r2eUbjoZAtp9wXk8gr0iU1s5rpkhMjIv0KPb7ekTH9nE2CUQkqo6Q3W4P16lSBDbS79nYvwikOXGxEh84rJm35M9ruTKR35XaRxSJuraNmgLHtMY38muakjqBzyqobTbtX7r+HmKOWQd4qOS2C+3a7r2+ENUU3CMBkTbssSuX8cRhcMxzP221fR2KwVeNK34mSB2sf+EnVzAuhqx1J6ndXBYZHp4YqZCSDiEiYQok+gp5dZu51At2dH0RQdHJhJaKqQVIWPlT1hCnTwu8n2/c+7wVgMD7TqSQDjTwQMSyKVZcjdI95aiVoBwGzxIEPCguKOPElKYk+PD1IQkHusyLGCT46TaMoR52ARr+jFB0CuNH+1M3466RNhoFf0sCDXYlv7kin2XVk
  template:
    metadata:
      creationTimestamp: null
      name: keto-db-url
      namespace: infra
    type: Opaque
