---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-credentials
  namespace: ingress
spec:
  encryptedData:
    cf-tunnel-token: AgAQtyynMA9c5+AUifXwd4LS/pQ5wpqPB3iFmZmldatnqWu4JDKNtM/kXEru9grJOY+yUbJpF1Z/TdGFSYrLmvZ27kUHz/XvDBaoI7Ow5L0MeWr+T+knqgqot4Sd/CSkZKugKDS7Gap7CJD+W6MCmq+0BV+prAP22oAsdLgCkAuBE/rb89EWDo+jQ9S4Ufk7yVzMRBJjKB9Y7ESk1bdkzVgmvQzdRo5beRcEL25Xy2ipzn3h4hvFl+4QPdIWgJIT+42l3ZUyquRKazEfN+R+OwE1r1vfSWR72WnsAaClN2OEzWUsySq1lqPz298WiaAR4zxtEBHgICtB+vIYZCqJh4IZeXHI43vdcw8YcxVv3lbPodaGarG5ft+WJT65XyYpuRLxb8oYexuyUSIy+6Ts625+54jDOVlnanunOP+7yVhjlgTVN/bX45x1s4GE3bWLzBE9UmbJWLBM7tLBEf2IJ19ip4sAOMy+UAUxrSVNl+iHB/iU2Ngg4E3Dj042nWooLx/r2cCmcXHrHfR3RZfBEl8AqrUeLEZOwAJIqOGQBWh4K/6+LedLNAxEp98N69ZXM5EChLLYtm5uu2kSUzhtcowtJchTrOhJ2yLpCma/KQiOo+v+FPuN0/PfxoX1+ItKVuljGxrDfUedmaWOIycBJXiLRLJY2RiQxTP/faHfaATvjIMtFQS6tvWeeM4aDe5QPj07z93lPjzvQPKETs2UC4XkV5crrUjNKuJ+XOlcohRVlCcAlWY6T2ZY1Kh1PfVjU6sCgaEIa5qiIjXDRyz15W9k1nPE0OHDBcmV1YORpLk38oNPDoOgRu56zMN+IDxxETfso3OIN2mGL21o+GAGlRn6pRRGNdElQ5mdb1HKKTOwALk3OTyT9RpP/B5oXVyyuKKIwo3XyW9yGYwclpJPJqkWPRKaPXIcUVzPO/4/2+z3786u7t5LRakJprw=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-credentials
      namespace: ingress
    type: Opaque
