apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ecoma-preview
  namespace: argocd
spec:
  description: Ecoma preview/PR environments applications
  sourceRepos:
    - https://github.com/ecoma-io/gitops.git
  destinations:
    - namespace: 'ecoma-preview-*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'